version: '3.8'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.2
    container_name: es8
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200

  # Servicio web opcional (descomentar si quieres que Django se ejecute en Docker)
  # web:
  #   build: .
  #   command: gunicorn library_project.wsgi:application --bind 0.0.0.0:8000
  #   volumes:
  #     - .:/code
  #   ports:
  #     - 8000:8000
  #   depends_on:
  #     - elasticsearch

volumes:
  esdata:
